name: Setting up Go environment
on:
  push:
jobs:
  setting-up-go:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: ['1.13', '1.14']
    name: Go ${{ matrix.go }} example
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
            go-version: ${{ matrix.go }}
        run: go version